name: codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
version: 1.0.0
homepage: https://github.com/stablekernel/dart-codable
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.4
